/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_RedLED_aliases.h"
#include "Pin_RedLED.h"
#include "PWM.h"
#include "Pin_GreenLED_aliases.h"
#include "Pin_GreenLED.h"
#include "Clock.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_Pins.h"
#include "CapSense_TunerHelper.h"
#include "CapSense_CompCH0.h"
#include "CapSense_IdacCH0.h"
#include "CapSense_AMuxCH0.h"
#include "CapSense_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

